version: '3.9'
services:

  redis-stack:
    image: redis/redis-stack:latest
    volumes:
      - redis-stack-data:/bitnami/redis/data
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - redisnet

  mongo:
    build: .
    image: mongocustom:1
    container_name: mongodb
    hostname: mongodb
    networks:
      - mongonet
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminp
    command: --config /etc/mongod.conf
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 20s
      timeout: 4s
      retries: 10
      start_period: 40s

  ##initialize mongo replicaset from another container ???
  mongoinit:
    build: .
    image: mongocustom:1
    hostname: mongodbinit
    container_name: mongodbinit
    networks:
      - mongonet
    depends_on:
      mongo:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --username admin --password adminp --authenticationDatabase admin --eval
      '
      rs.initiate();
      '

volumes:
  redis-stack-data:
    driver: local


networks:
  redisnet: {}
  mongonet: {}

